package pheriperals;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class Pheriperaltable extends javax.swing.JFrame {

    /**
     * Creates new form Pheriperaltable
     */
    public Pheriperaltable() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbemp = new javax.swing.JTable();
        jEmpName = new javax.swing.JLabel();
        tfempname = new javax.swing.JTextField();
        jPheriperals = new javax.swing.JLabel();
        tfpheriperal = new javax.swing.JComboBox<>();
        jcode = new javax.swing.JLabel();
        tfcode = new javax.swing.JTextField();
        jadd = new javax.swing.JButton();
        jupdate = new javax.swing.JButton();
        jdelete = new javax.swing.JButton();
        jMessage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jType = new javax.swing.JLabel();
        joutputinput = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        tbemp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Employee Name", "Pheriperals", "Types", "code"
            }
        ));
        tbemp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbempMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbemp);

        jEmpName.setText("Employee NAME");

        tfempname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfempnameActionPerformed(evt);
            }
        });

        jPheriperals.setText("Pheriperals");

        tfpheriperal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mouse", "Speaker", "Keyboard", "Monitor", "Printer", "web cam" }));

        jcode.setText("Code");

        jadd.setText("Add");
        jadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddActionPerformed(evt);
            }
        });

        jupdate.setText("update");
        jupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jupdateActionPerformed(evt);
            }
        });

        jdelete.setText("delete");
        jdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jdeleteActionPerformed(evt);
            }
        });

        jMessage.setForeground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Onofre AND Suico.com");

        jType.setText("Type");

        joutputinput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Output", "Input" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(275, 275, 275)
                .addComponent(jdelete)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jEmpName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(23, 23, 23)
                                .addComponent(tfempname, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPheriperals)
                                            .addComponent(jcode, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 71, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jadd)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfpheriperal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfcode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jupdate)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jType)
                                .addGap(18, 18, 18)
                                .addComponent(joutputinput, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jMessage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jEmpName)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfempname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPheriperals)
                    .addComponent(tfpheriperal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jType)
                    .addComponent(joutputinput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcode))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jadd)
                    .addComponent(jupdate)
                    .addComponent(jdelete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 9, Short.MAX_VALUE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>                        

    private void jaddActionPerformed(java.awt.event.ActionEvent evt) {                                     
        jMessage.setText("");
        DefaultTableModel model=(DefaultTableModel) tbemp.getModel ();
       if(!tfempname.getText().trim().equals("")){
       model.addRow(new Object[]{tfempname.getText(),tfpheriperal.getSelectedItem().toString(),joutputinput.getSelectedItem().toString(),tfcode.getText()});
       
       } else{ jMessage.setText("Employee name should not left blank please ");
       
       }
       if(tfempname.getText().trim().equals("")&&tfcode.getText().equals("")){
           JOptionPane.showMessageDialog(null, "WRONG ENTRY");  
       } else{
           JOptionPane.showMessageDialog(null, "Succesfully added"); 
       }
        
           
 
    }                                    

    private void jupdateActionPerformed(java.awt.event.ActionEvent evt) {                                        
       jMessage.setText("");
        DefaultTableModel model=(DefaultTableModel) tbemp.getModel ();
       if(tbemp.getSelectedRow()==-1){
        if(tbemp.getSelectedRow()==-0){
         jMessage.setText("this table is empty, To update select product and change product name,code,types ");   
        }else{
            jMessage.setText("You must Select a Product and change product name in console to update ");
        
        }  
       }else{
       model.setValueAt(tfempname.getText(),tbemp.getSelectedRow(), 0);
        model.setValueAt(tfpheriperal.getSelectedItem().toString(),tbemp.getSelectedRow(), 1);
         model.setValueAt(joutputinput.getSelectedItem().toString(),tbemp.getSelectedRow(), 2);
          model.setValueAt(tfcode.getText(),tbemp.getSelectedRow(), 3);
       }
        if(tfempname.getText().trim().equals("")&&tfcode.getText().equals("")){
           JOptionPane.showMessageDialog(null, "WRONG ENTRY");  
       } else{
           JOptionPane.showMessageDialog(null, "Succesfully updated"); 
       }
           
    }                                       

    private void formMouseClicked(java.awt.event.MouseEvent evt) {                                  
       
    }                                 

    private void tbempMouseClicked(java.awt.event.MouseEvent evt) {                                   
 DefaultTableModel model=(DefaultTableModel) tbemp.getModel ();
      tfempname.setText(model.getValueAt(tbemp.getSelectedRow(), 0) .toString());
      tfpheriperal.setSelectedItem(model.getValueAt(tbemp.getSelectedRow(), 1) .toString());
    joutputinput.setSelectedItem(model.getValueAt(tbemp.getSelectedRow(), 1) .toString());
      tfcode.setText(model.getValueAt(tbemp.getSelectedRow(), 3) .toString());
    }                                  

    private void jdeleteActionPerformed(java.awt.event.ActionEvent evt) {                                        
        DefaultTableModel model=(DefaultTableModel) tbemp.getModel ();
         if(tbemp.getSelectedRow()==-1){
        if(tbemp.getSelectedRow()==-0){
         jMessage.setText("this table is empty ");   
        }else{
            jMessage.setText("You must Select a Product ");
        
        }  
       }else{
       model.removeRow(tbemp.getSelectedRow());
       }
         if(tfempname.getText().trim().equals("")&&tfcode.getText().equals("")){
           JOptionPane.showMessageDialog(null, "Succesfully Deleted");  
       } else{
           JOptionPane.showMessageDialog(null, "Succesfully Deleted"); 
       }
       
    }                                       

    private void tfempnameActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pheriperaltable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pheriperaltable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pheriperaltable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pheriperaltable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pheriperaltable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jEmpName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jMessage;
    private javax.swing.JLabel jPheriperals;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jType;
    private javax.swing.JButton jadd;
    private javax.swing.JLabel jcode;
    private javax.swing.JButton jdelete;
    private javax.swing.JComboBox<String> joutputinput;
    private javax.swing.JButton jupdate;
    private javax.swing.JTable tbemp;
    private javax.swing.JTextField tfcode;
    private javax.swing.JTextField tfempname;
    private javax.swing.JComboBox<String> tfpheriperal;
    // End of variables declaration                   

   
}
